In [1]:
# Load library
from sklearn.feature_extraction import DictVectorizer

In [2]:
# Our dictionary of data
data_dict = [{'Red': 2, 'Blue': 4},
             {'Red': 4, 'Blue': 3},
             {'Red': 1, 'Yellow': 2},
             {'Red': 2, 'Yellow': 2}]

In [8]:
data_dict

[{'Blue': 4, 'Red': 2},
 {'Blue': 3, 'Red': 4},
 {'Red': 1, 'Yellow': 2},
 {'Red': 2, 'Yellow': 2}]

In [12]:
# Create DictVectorizer object
dictvectorizer = DictVectorizer(sparse=False)
print(dictvectorizer)

DictVectorizer(dtype=<class 'numpy.float64'>, separator='=', sort=True,
        sparse=False)


In [13]:
# Convert dictionary into feature matrix
features = dictvectorizer.fit_transform(data_dict)
print(features)

[[ 4.  2.  0.]
 [ 3.  4.  0.]
 [ 0.  1.  2.]
 [ 0.  2.  2.]]


In [14]:
# View feature matrix column names
dictvectorizer.get_feature_names()

['Blue', 'Red', 'Yellow']